import {
  Breadcrumbs,
  Cards,
  Carousels,
  Collapses,
  Dropdowns,
  Forms,
  Jumbotrons,
  ListGroups,
  Navbars,
  Navs,
  Paginations,
  Popovers,
  ProgressBar,
  Switches,
  Tables,
  Tabs,
  Tooltips,
  Test,
  Excels,
  ScheduleParameters,
  Company,
  ChangePassword,
  Invitation,
  Invitation_Detail,
  Invitation_Create,
  Ojt_Registration,
  CV,
  student_list,
  business_list,
} from './Base';

import { ButtonDropdowns, ButtonGroups, Buttons, BrandButtons } from './Buttons';
import Charts from './Charts';
import Dashboard from './Dashboard';
import { CoreUIIcons, Flags, FontAwesome, SimpleLineIcons } from './Icons';
import { Alerts, Badges, Modals } from './Notifications';
import { Login, Page404, Page500, ForgotPassword } from './Pages';
import { Colors, Typography } from './Theme';
import Widgets from './Widgets';
import Official_List from "./Official_List/Official_List";
import Details_Task from "./Details_Task/Details_Task";
import Job_Post from "./Job_Post/Job_Post";

export {
  Badges,
  Typography,
  Colors,
  CoreUIIcons,
  Page404,
  Page500,
  ForgotPassword,
  Login,
  Modals,
  Alerts,
  Flags,
  SimpleLineIcons,
  FontAwesome,
  ButtonDropdowns,
  ButtonGroups,
  BrandButtons,
  Buttons,
  Tooltips,
  Tabs,
  Tables,
  Charts,
  Dashboard,
  Widgets,
  Jumbotrons,
  Switches,
  ProgressBar,
  Popovers,
  Navs,
  Navbars,
  ListGroups,
  Forms,
  Dropdowns,
  Collapses,
  Carousels,
  Cards,
  Breadcrumbs,
  Paginations,
  Test,
  Excels,
  ScheduleParameters,
  Company,
  ChangePassword,
  Invitation,
  Invitation_Detail,
  Invitation_Create,
  Ojt_Registration,
  CV,
  student_list,
  business_list,
  Official_List,
  Details_Task,
  Job_Post,
};

